<?xml version="1.0" encoding="utf-8"?><Database Name="ENAGAS" Class="BaseDeDatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-H26444U\SQLEXPRESS;Initial Catalog=ENAGAS;Integrated Security=True" SettingsObjectName="PROJECT_ENA_GAS.Properties.Settings" SettingsPropertyName="ENAGASConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="EnaGas.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contraseña" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cargo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="EnaGas.Cargo" Member="Cargo">
    <Type Name="Cargo">
      <Column Name="idCargo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo" Member="cargoUsuario" Storage="_cargo1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="EnaGas.Chimbo" Member="Chimbo">
    <Type Name="Chimbo">
      <Column Name="idChimbo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="peso" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="EnaGas.Inventario" Member="Inventario">
    <Type Name="Inventario">
      <Column Name="idCantidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="EnaGas.ClientesEna" Member="ClientesEna">
    <Type Name="ClientesEna">
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identidad" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="peso" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>