USE tempdb
GO

IF NOT EXISTS(SELECT * FROM sys.databases WHERE [name] = 'ENAGAS')
	BEGIN
		CREATE DATABASE ENAGAS
	END
GO

USE ENAGAS
GO

CREATE SCHEMA EnaGas
GO

CREATE TABLE EnaGas.Clientes(
idCliente INT IDENTITY(1,1) PRIMARY KEY CLUSTERED NOT NULL,
identidad VARCHAR(13)NOT NULL,
nombre NVARCHAR(50)NOT NULL,
apellido NVARCHAR(50)NOT NULL,
direccion NVARCHAR(100)NOT NULL,
telefono VARCHAR(20)
)
GO

CREATE TABLE EnaGas.Inventario(
idCantidad INT IDENTITY(1,1)NOT NULL PRIMARY KEY CLUSTERED,
cantidad INT
)
GO


CREATE TABLE EnaGas.Chimbo(
idChimbo INT IDENTITY(1,1)NOT NULL,
idCantidad INT,
peso VARCHAR(20)NOT NULL,
precio MONEY NOT NULL
)
GO

CREATE TABLE EnaGas.Usuario(
idUsuario INT IDENTITY(1,100)NOT NULL PRIMARY KEY CLUSTERED,
nombreUsuario NVARCHAR(100)NOT NULL,
contraseña NVARCHAR(100)NOT NULL,
cargo NVARCHAR(50)NOT NULL
)
GO

ALTER TABLE EnaGas.Chimbo
ADD CONSTRAINT FK_EnaGas_Chimbo_Id$TieneUna$EnaGas_Inventario
FOREIGN KEY (idCantidad) REFERENCES EnaGas.Inventario(idCantidad)
ON UPDATE NO ACTION
ON DELETE CASCADE
GO